# 侧边菜单
sidebar:
    主页: 
      href: /
      icon: home
    关于:
      href: /about/
      icon: person
scripts:
  - /js/mdui.min.js
  - /js/lenis.min.js
  - /js/global.js

stylesheets:
  - /css/mdui.min.css
  - /css/global.css
  - /css/lenis.min.css
